### ISSUE TITLE
routeNotFound method seems to be missing

### ISSUE THREAD

**Issue by mjclemente** [coldbox-templates/rest-hmvc#6]
The docs mention a `routeNotFound` [utility function](https://github.com/coldbox-templates/rest-hmvc#utility-functions).

I'm not seeing that in the baseHander. Was the method every created/implemented?

**Comment by mjclemente** [comment]
Did a little more digging and just noticed `onInvalidRoute` - perhaps that's what this was supposed to be?

**Comment by lmajano** [comment]
where was this?

**Comment by mjclemente** [comment]
The [README](https://github.com/coldbox-templates/rest-hmvc/blob/master/readme.md)

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5348419/70090571-705d9a80-15e8-11ea-855f-bd2a08174d0b.png">

**Comment by lmajano** [comment]
ahh yes, then we need to update
